[package]
name = "m6binpack-procmacro"
version = "0.1.0"
edition = "2018"

[dependencies]
proc-macro2 = "^1.0"
quote = "^1.0"
syn = { version = "^1.0", features = ["extra-traits"] }

[lib]
proc-macro = true
