[package]
name = "proc_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "^1.0"
quote = "^1.0"
syn = { version = "^1.0", features = ["extra-traits"] }

[dev-dependencies]
m6binpack = { path = "../" }

[lib]
proc-macro = true
