[package]
name = "m6binpack"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.proc_macros]
path = "proc_macros"
version = "0.1.0"  # Same as main

[workspace]
members = ["proc_macros"]
